

POST http://localhost:3000/tags
Content-Type: application/json
Authorization: Bearer token

{
  "name": "Javascript",
  "slug": "javascript",
  "description": "This is a description of the tag",
  "schema": "This is a schema of the tag",
  "featuredImageUrl": "https://example.com/image.jpg"
}