### Create a new meta option
POST http://localhost:3000/meta-options
Content-Type: application/json

{
  "metaValue": "{\"key\": \"value\", \"number\": 123, \"boolean\": true}"
}

### Get all meta options
GET http://localhost:3000/meta-options

### Get a specific meta option by ID
GET http://localhost:3000/meta-options/1

### Update a meta option
PUT http://localhost:3000/meta-options/1
Content-Type: application/json

{
  "metaValue": "{\"key\": \"updated value\", \"number\": 456, \"boolean\": false}"
}

### Delete a meta option
DELETE http://localhost:3000/meta-options/1
